### ISSUE TITLE
Value size reshape

### ISSUE THREAD

**Issue by zimingzhong** [DSaurus/threestudio-3dgs#17]
When i run `python launch.py --config custom/threestudio-3dgs/configs/gaussian_splatting.yaml  --train --gpu 0 system.prompt_processor.prompt="a delicious hamburger"` 

https://github.com/threestudio-project/threestudio/blob/d85e1f8dfdcc1a8015fbedc6b9c213653a47c219/threestudio/models/guidance/stable_diffusion_guidance.py#L267-L270

`alpha = self.alphas[t] ** 0.5`
 ` sigma = (1 - self.alphas[t]) ** 0.5`
  `latents_denoised = (latents_noisy - sigma * noise_pred) / alpha`
 ` image_denoised = self.decode_latents(latents_denoised)
`

get error: latents denoise = (latents noisy - sigma * noise_pred) / alpha *** RuntimeError: The size of tensor a (4) must match the size of tensor b (64) at non-singleton dimension 3
i change it to 
`alpha = self.alphas[t] ** 0.5`
  `alpha = alpha.view(-1, 1, 1, 1)`
  `sigma = (1 - self.alphas[t]) ** 0.5`
  `sigma = sigma.view(-1, 1, 1, 1)`
  `latents_denoised = (latents_noisy - sigma * noise_pred) / alpha`
  `image_denoised = self.decode_latents(latents_denoised)
`
then the code can run
is that right?

**Comment by DSaurus** [comment]
Hi @zimingzhong ,

Thank you for pointing out this bug! I have fixed it in the latest commit.

**Comment by zimingzhong** [comment]
> Hi @zimingzhong ,
> 
> Thank you for pointing out this bug! I have fixed it in the latest commit.

Thank you for your quick reply. I provide a pull on threestudio[threestudio](https://github.com/threestudio-project/threestudio/pull/399). You can directly add it.
